name: 'reverse-proxy'
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./conf:/etc/caddy:z"
      - "caddy_data:/data:z"
      - "caddy_config:/config"
    environment:
      DOMAIN: "${DOMAIN}"
      CONTROLLER_URI: "${CONTROLLER_URI}"
      PROXIED_URI: "${PROXIED_URI}"
      SSL_EMAIL: "${SSL_EMAIL}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

volumes:
  caddy_data:
  caddy_config: