name: 'controller'
version: '3'
services:
  db:
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: postgres:18.3-alpine
    ports:
      - "${EXTERNAL_PORT}:5432"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${EXTERNAL_PORT}/${POSTGRES_DB}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      PHX_HOST: "${PHX_HOST}"
    ports:
      - "4000:4000"