[env]
EXTERNAL_PORT="15432"
POSTGRES_DB="controller_dev"
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="postgres"
SECRET_KEY_BASE="DUMMY_SECRET_KEY_DUMMY_SECRET_KEY_DUMMY_SECRET_KEY_DUMMY_SECRET_KEY_DUMMY_SECRET_KEY_DUMMY_SECRET_KEY"
PHX_HOST="localhost"