[env]
DOMAIN="localhost"
POSTGRES_DB="controller_dev"
POSTGRES_HOST="localhost"
POSTGRES_USER="postgres"
POSTGRES_PORT="5432"
POSTGRES_PASSWORD="postgres"

# CHATTERBOX_PORT=""
# CHATTERBOX_REMOTE_PATH=""
# CHATTERBOX_SYSTEM_MAC_ADDRESS=""
# SECRET_KEY_BASE=""
# SSH_HOSTNAME=""
# SSH_PORT=""
# SSH_PRIVATE_KEY=""
# SSH_REMOTE_USER=""