[env]
DOMAIN="localhost"
POSTGRES_DB="controller_dev"
POSTGRES_USER="postgres"
POSTGRES_PORT="15432"
POSTGRES_PASSWORD="postgres"
WOL_ALIAS="wakeonlan"

# CHATTERBOX_PORT=""
# CHATTERBOX_REMOTE_PATH=""
# CHATTERBOX_SYSTEM_MAC_ADDRESS=""
# CONNECTION_INTERFACE=""
# CONNECTION_TYPE=""
# SECRET_KEY_BASE=""
# SSH_HOSTNAME=""
# SSH_PORT=""
# SSH_PRIVATE_KEY=""
# SSH_REMOTE_USER=""